<?php
    return [
        'url'   => [
            'prefix_backend'    => 'admin',
            'prefix_frontend'   =>  ''
        ],
        'format'                =>  [
            'long_time'         => 'H:m:s - d/m/Y',
            'short_time'        => 'd/m/Y',
        ],
        'template' => [
            'status'            =>  [
                
                'all'           =>  [    'name' => 'Tất cả'          ,   'class' => 'btn-info'       ],
                'default'       =>  [    'name' => 'Chờ duyệt'          ,   'class' => 'btn-info'    ],
                '1'             =>  [    'name' => 'Kích hoạt'       ,   'class' => 'btn-success'    ],
                '0'             =>  [    'name' => 'Chưa kích hoạt'  ,   'class' => 'btn-info'       ],                 
            ],
            'status_applied'    =>  [
                'default'       =>  [    'name' => 'Chờ xét duyệt'  ],  
                '1'        =>  [    'name' => 'Chấp nhận'      ],
                '0'       =>  [    'name' => 'Từ chối'         ],                                
            ],
            'search'            =>  [
                'all'           =>  [    'name' => 'Search by All'               ],
                'id'            =>  [    'name' => 'Search by ID'                ],
                'username'      =>  [    'name' => 'Search by Username'          ],
                'fullname'      =>  [    'name' => 'Search by Fullname'          ],
                'email'         =>  [    'name' => 'Search by Email'             ],                
                'title'         =>  [    'name' => 'Search by Title'             ],
                'content'       =>  [    'name' => 'Search by Content'           ],
            ],
            'button'            =>  [
                'edit'          =>  ['class' => 'btn-success'               ,   'title' => 'Chỉnh sửa'       ,   'icon' => 'fa-pencil'   ,   'route-name' => '/form'       ],
                'delete'        =>  ['class' => 'btn-info btn-delete'       ,   'title' => 'Xoá'             ,   'icon' => 'fa-trash'    ,   'route-name' => '/delete'     ],
                'info'          =>  ['class' => 'btn-info'                  ,   'title' => 'Info'            ,   'icon' => 'fa-trash'    ,   'route-name' => '/delete'     ],
            ],
            'form_input'        =>  [
                'class'         =>  'form-control col-md-6 col-xs-12'
            ],
            'form_label'        =>  [
                'class'         =>  'control-label col-md-3 col-sm-3 col-xs-12'
            ],
            'form_ckeditor'     =>  [
                'class'         =>  'ckeditor'
            ],
            'type'              =>  [
                '1'             =>  [    'name' => 'Thường'             ],
                '0'             =>  [    'name' => 'Nổi bật'            ],                
            ],
            'company_size'      =>  [
                '1'             =>  [    'name' => 'Dưới 10'        ],
                '2'             =>  [    'name' => 'Từ 10 - 24'     ],          
                '3'             =>  [    'name' => 'Từ 25 - 99'     ],        
                '4'             =>  [    'name' => 'Từ 100 - 499'   ],  
                '5'             =>  [    'name' => 'Từ 500 - 999'   ],  
                '6'             =>  [    'name' => 'Từ 1000 - 4999' ],  
                '7'             =>  [    'name' => 'Từ 5000 - 9999' ],  
                '8'             =>  [    'name' => 'Trên 10000'     ],  
            ],
            'career'        =>  [
                '1'             =>  [    'name' => 'Bán hàng / Tiếp thị'    ],
                '2'             =>  [    'name' => 'Nhà đất / BĐS'          ],          
                '3'             =>  [    'name' => 'Kỹ thuật'               ],          
                '4'             =>  [    'name' => 'Dịch vụ'                ],   
                '5'             =>  [    'name' => 'Máy tính / IT'          ],
                '6'             =>  [    'name' => 'Chăm sóc sức khỏe'      ],          
                '7'             =>  [    'name' => 'Sản xuất' ], 
                '8'             =>  [    'name' => 'Hành chính / Nhân sự'   ],
                '9'             =>  [    'name' => 'Kế toán / Tài chính'    ],          
                '10'            =>  [    'name' => 'Truyền thông / Media'   ], 
                '11'            =>  [    'name' => 'Xây dựng'               ],
                '12'            =>  [    'name' => 'Giáo dục / Đào tạo'     ],          
                '13'            =>  [    'name' => 'Khoa học'               ], 
                '14'            =>  [    'name' => 'Khách sạn / Du lịch'    ],
                '15'            =>  [    'name' => 'Ngành khác'             ],
            ],
            'city'              =>  [
                '1'             =>  [    'name' => 'Thành phố Hà Nội'],
                '2'             =>  [    'name' => 'Tỉnh Hà Giang' ], 
                '3'             =>  [    'name' => 'Tỉnh Cao Bằng' ],   
                '4'             =>  [    'name' => 'Tỉnh Bắc Kạn'],
                '5'             =>  [    'name' => 'Tỉnh Tuyên Quang' ], 
                '6'             =>  [    'name' => 'Tỉnh Lào Cai' ],  
                '7'             =>  [    'name' => 'Tỉnh Điện Biên'],
                '8'             =>  [    'name' => 'Tỉnh Lai Châu' ], 
                '9'             =>  [    'name' => 'Tỉnh Sơn La' ],  
                '10'            =>  [    'name' => 'Tỉnh Yên Bái'],
                '11'            =>  [    'name' => 'Tỉnh Hoà Bình' ], 
                '12'            =>  [    'name' => 'Tỉnh Thái Nguyên' ],  
                '13'            =>  [    'name' => 'Tỉnh Lạng Sơn'],
                '14'            =>  [    'name' => 'Tỉnh Quảng Ninh' ], 
                '15'            =>  [    'name' => 'Tỉnh Bắc Giang' ],  
                '16'            =>  [    'name' => 'Tỉnh Phú Thọ'],
                '17'            =>  [    'name' => 'Tỉnh Vĩnh Phúc' ], 
                '18'            =>  [    'name' => 'Tỉnh Bắc Ninh' ], 
                '19'            =>  [    'name' => 'Tỉnh Hải Dương' ], 
                '20'            =>  [    'name' => 'Thành phố Hải Phòng' ],    
                '21'            =>  [    'name' => 'Tỉnh Hưng Yên'],
                '22'            =>  [    'name' => 'Tỉnh Thái Bình' ], 
                '23'            =>  [    'name' => 'Tỉnh Hà Nam' ],   
                '24'            =>  [    'name' => 'Tỉnh Nam Định'],
                '25'            =>  [    'name' => 'Tỉnh Ninh Bình' ], 
                '26'            =>  [    'name' => 'Tỉnh Thanh Hóa' ],  
                '27'            =>  [    'name' => 'Tỉnh Nghệ An'],
                '28'            =>  [    'name' => 'Tỉnh Hà Tĩnh' ], 
                '29'            =>  [    'name' => 'Tỉnh Quảng Bình' ],  
                '30'            =>  [    'name' => 'Tỉnh Quảng Trị'],
                '31'            =>  [    'name' => 'Tỉnh Thừa Thiên Huế' ], 
                '32'            =>  [    'name' => 'Thành phố Đà Nẵng' ],  
                '33'            =>  [    'name' => 'Tỉnh Quảng Nam'],
                '34'            =>  [    'name' => 'Tỉnh Quảng Ngãi' ], 
                '35'            =>  [    'name' => 'Tỉnh Bình Định' ],  
                '36'            =>  [    'name' => 'Tỉnh Phú Yên'],
                '37'            =>  [    'name' => 'Tỉnh Khánh Hòa' ], 
                '38'            =>  [    'name' => 'Tỉnh Ninh Thuận' ], 
                '39'            =>  [    'name' => 'Tỉnh Bình Thuận' ], 
                '40'            =>  [    'name' => 'Tỉnh Kon Tum' ],   
                '41'            =>  [    'name' => 'Tỉnh Gia Lai' ], 
                '42'            =>  [    'name' => 'Tỉnh Đắk Lắk' ],  
                '43'            =>  [    'name' => 'Tỉnh Đắk Nông'],
                '44'            =>  [    'name' => 'Tỉnh Lâm Đồng' ], 
                '45'            =>  [    'name' => 'Tỉnh Bình Phước' ],  
                '46'            =>  [    'name' => 'Tỉnh Tây Ninh'],
                '47'            =>  [    'name' => 'Tỉnh Bình Dương' ], 
                '48'            =>  [    'name' => 'Tỉnh Đồng Nai' ], 
                '49'            =>  [    'name' => 'Tỉnh Bà Rịa - Vũng Tàu' ], 
                '50'            =>  [    'name' => 'Thành phố Hồ Chí Minh' ], 
                '51'            =>  [    'name' => 'Tỉnh Long An' ], 
                '52'            =>  [    'name' => 'Tỉnh Tiền Giang' ],  
                '53'            =>  [    'name' => 'Tỉnh Bến Tre'],
                '54'            =>  [    'name' => 'Tỉnh Trà Vinh' ], 
                '55'            =>  [    'name' => 'Tỉnh Vĩnh Long' ],  
                '56'            =>  [    'name' => 'Tỉnh Đồng Tháp'],
                '57'            =>  [    'name' => 'Tỉnh An Giang' ], 
                '58'            =>  [    'name' => 'Tỉnh Kiên Giang' ], 
                '59'            =>  [    'name' => 'Thành phố Cần Thơ' ], 
                '60'            =>  [    'name' => 'Tỉnh Hậu Giang' ],
                '61'            =>  [    'name' => 'Tỉnh Sóc Trăng' ],
                '62'            =>  [    'name' => 'Tỉnh Bạc Liêu' ],
                '63'            =>  [    'name' => 'Tỉnh Cà Mau' ],
            ],
            'district'          =>  [
                '1'             =>  [    'name' => 'Quận Ba Đình'],
                '2'             =>  [    'name' => 'Quận Tây Hồ' ],          
                '3'             =>  [    'name' => 'Quận Long Biên' ],        
            ],
            'ward'              =>  [
                '1'             =>  [    'name' => 'Phường Phúc Xá'     ],
                '2'             =>  [    'name' => 'Phường Trúc Bạch'   ],          
                '3'             =>  [    'name' => 'Phường Vĩnh Phúc'   ],        
            ],
            'salary'            =>  [
                '1'             =>  [    'name' => 'Từ 1 đến 3 triệu'   ],
                '2'             =>  [    'name' => 'Từ 3 đến 5 triệu'   ],          
                '3'             =>  [    'name' => 'Từ 5 đến 7 triệu'   ],
                '4'             =>  [    'name' => 'Từ 7 đến 10 triệu'  ],     
                '5'             =>  [    'name' => 'Trên 10 triệu'      ],  
            ],
            'experience'        =>  [
                '1'             =>  [    'name' => 'Chưa có kinh nghiệm'    ],
                '2'             =>  [    'name' => 'Dưới 1 năm'             ],          
                '3'             =>  [    'name' => 'Từ 1 đến 2 năm'         ],       
                '4'             =>  [    'name' => 'Từ 2 đến 3 năm'         ],
                '5'             =>  [    'name' => 'Từ 3 đến 4 năm'         ],          
                '6'             =>  [    'name' => 'Từ 4 đến 5 năm'         ],  
                '7'             =>  [    'name' => 'Trên 5 năm'             ],  
            ],
            'gender'            =>  [
                '1'             =>  [    'name' => 'Nam'                    ],
                '2'             =>  [    'name' => 'Nữ'                     ],          
                '3'             =>  [    'name' => 'Không yêu cầu'          ],        
            ],            
            'level'             =>  [
                '1'             =>  [    'name' => 'Cao học'                ],
                '2'             =>  [    'name' => 'Đại học'                ],          
                '3'             =>  [    'name' => 'Cao đẳng'               ],
                '4'             =>  [    'name' => 'Trung cấp'              ],
                '5'             =>  [    'name' => 'Trung học'              ],          
                '6'             =>  [    'name' => 'Chứng chỉ'              ], 
                '7'             =>  [    'name' => 'Lao động phổ thông'     ], 
            ],
            'work_type'         =>  [
                '1'             =>  [    'name' => 'Nhân viên chính thức'   ],
                '2'             =>  [    'name' => 'Nhân viên thời vụ'      ],          
                '3'             =>  [    'name' => 'Bán thời gian'          ],     
                '4'             =>  [    'name' => 'Làm thêm ngoài giờ'     ],          
                '5'             =>  [    'name' => 'Thực tập và dự án'      ],      
            ]
        ],
        'config'                =>  [
            'search'            =>  [
                'default'       =>  ['all', 'id'                            ],
                'recruit'       =>  ['all', 'username', 'fullname', 'email' ],
                'job'           =>  ['all', 'title'                         ],
                'candidate'     =>  ['all', 'username', 'fullname',         ],
                'user'          =>  ['all', 'username', 'fullname',         ],
            ],
            'button'            =>  [
                'default'       =>  ['edit' , 'delete'              ],
                'recruit'       =>  ['edit' , 'delete'              ],
                'job'           =>  ['edit' , 'delete'              ],
                'candidate'     =>  ['edit' , 'delete'              ],
                'user'          =>  ['edit' , 'delete'              ]
            ]
        ]
    ];